### ISSUE TITLE
Images supported?

### ISSUE THREAD

**Issue by brycewray** [d4rekanguok/gatsby-schema-field-absolute-path#2]
Nice work; surely seems to resolve a frequent stumbling block with Gatsby for those used to more traditional Web directory structures. Does this work also with (a.) images called from Markdown body copy rather than front matter and/or (b.) background images?

**Comment by d4rekanguok** [comment]
Thank you @brycewray! (I've just seen your RT of the article, thanks so much!)

**a. Images in markdown body**

These are unknown to Gatsby's schema, so this plugin can't help there.

The good news is there's another plugin that solves this for images referenced from both inside Markdown body copy _and_ in frontmatter: [gatsby-remark-relative-images](https://github.com/danielmahon/gatsby-remark-relative-images). You can use this plugin in conjunction with the default `gatsby-relative-images` to be able to place images wherever you please.

Personally, when it comes to resolving path in frontmatter, I find `gatsby-remark-relative-images`'s approach a bit heavy-handed: It'll recursively try to modify the path-like value of every field. 

Because of this, I've been working on a more flexible plugin to handle images in Markdown: [`gatsby-remark-images-anywhere`](https://github.com/d4rekanguok/gatsby-remark-images-anywhere). It also works with remote images, which makes me happy.

**b. Background images**

**In Markdown**
None of the plugins I shared above deal with background images in Markdown, however, it's a solvable problem. If you'd like, we can open an issue for that over `gatsby-remark-images-anywhere`.

**Elsewhere**
For general background images, you can use `gatsby-schema-field-absolute-path` in conjunction with [`gatsby-background-image`](https://github.com/timhagn/gatsby-background-image) to put your images anywhere you'd like!

**Comment by brycewray** [comment]
@d4rekanguok Thanks for the detailed reply! I actually do already use both `gatsby-background-image` and `gatsby-remark-relative-images`, but your new plugin seems so cool, and seems to solve so many problems that Gatsby noobs like me encounter, I was just hoping it could handle those capabilities as well. Nonetheless, well done, sir. I would love for Gatsby to make this part of core; I believe it’s that smart and necessary. Thank you also for the many excellent replies I’ve seen you give on Stack Overflow — we Gatsby noobs need more like you in the community! Best wishes, sir.

**Comment by d4rekanguok** [comment]
Thank you, you're too kind!
